<dialog id="registration-dialog" class="animation-speed-normal animation-ease-in-out fade-in">
	<form name="registration" action="register.php">
		<fieldset>
			<div>
				<input type="text" name="Person[name]" autocomplete="name" placeholder="Full name" required="" />
			</div>
			<div>
				<input type="tel" name="Person[telephone]" autocomplete="telephone" placeholder="+1-555-555-5555" />
			</div>
			<div>
				<input type="email" name="Person[email]" autocomplete="email" placeholder="user@example.com" required="" />
			</div>
			<div>
				<input type="password" name="Person[password]" autocomplete="new-password" placeholder="********" minlength="12" required="" />
			</div>
		</fieldset>
		<button type="submit" class="btn-go">Submit</button>
		<button type="reset" class="btn-danger" data-close="#registration-dialog">Cancel</button>
	</form>
</dialog>
